buildscript
{
	repositories
	{
		jcenter()
		maven { url = "https://files.minecraftforge.net/maven" }
	}
	dependencies
	{
        classpath 'net.minecraftforge.gradle:ForgeGradle:3.+'
	}
}

apply plugin: 'net.minecraftforge.gradle'
apply plugin: 'java'
sourceCompatibility = targetCompatibility = compileJava.sourceCompatibility = compileJava.targetCompatibility = '1.8'
project.mkdir "libs"

version = mod_version
group = mod_group
archivesBaseName = mod_name


minecraft {

    mappings channel: 'snapshot', version: '20171003-1.12'
    runs {
        client {
            workingDirectory project.file('run')

            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'

            property 'forge.logging.console.level', 'debug'
        }

        server {

            property 'forge.logging.markers', 'SCAN,REGISTRIES,REGISTRYDUMP'

            property 'forge.logging.console.level', 'debug'
        }
    }

}

task debugClient {
    group = 'Minecraft'
    description = 'Run Minecraft client with debugger attached. Used for VSCode'
    doFirst
	{
		runClient.jvmArgs+= ["-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005"]
	}
	finalizedBy 'runClient'
}

task debugServer {
    group = 'Minecraft'
    description = 'Run Minecraft server with debugger attached. Used for VSCode'
    
    doFirst
	{
		runServer.jvmArgs+= ["-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005"]
	}
	finalizedBy 'runServer'
}

repositories
{
	maven
	{
		name 'Progwml6'
		url "http://dvs1.progwml6.com/files/maven"
	}
	
		maven
		{
			name = 'sponge'
			url = 'https://repo.spongepowered.org/repository/maven-public/'
		}
    maven { url = 'https://www.cursemaven.com' } // For CurseForge mods

}

dependencies
{
    //runtime ("curse.maven:jei-238222:2640458")
   compile ("org.spongepowered:mixin:${mixin_version}")

        minecraft 'net.minecraftforge:forge:1.12.2-14.23.5.2854'
}

processResources
{
    inputs.property "version", project.version
    from(sourceSets.main.resources.srcDirs)
    {
        include 'mcmod.info'
    }
}

jar
{
	from {configurations.compileClasspath.filter {"mixin-${mixin_version}.jar" == it.name}.collect{it.isDirectory() ? it : zipTree(it)}}
	{
		exclude 'dummyThing', 'LICENSE.txt', 'module-info.class', 'META-INF/MANIFEST.MF', 'META-INF/maven/**', 'META-INF/*.RSA', 'META-INF/*.SF'
	}
	manifest.attributes (
			'FMLAT': "${mod_id}_at.cfg",
			'TweakClass': 'org.spongepowered.asm.launch.MixinTweaker',
			'MixinConfigs': "META-INF/${mod_id}_mixin.json",
			'FMLCorePluginContainsFMLMod': 'true'
	)
	finalizedBy 'reobfJar'
}